module.exports = {
    CLIENT_ID: 'ID OF CLIENT',
    HAMMYS_ID: 'ID OF HAMMY',
    TWITTER: {
        CONSUMER_KEY: 'TWITTER CONSUMER KEY',
        CONSUMER_SECRET: 'TWITTER CONSUMER SECRET',
        ACCESS_TOKEN: 'TWITTER ACCESS TOKEN',
        ACCESS_TOKEN_SECRET: 'TWITTER ACCESS TOKEN SECRET'
    }
};
